# This is a basic workflow to help you get started with Actions

name: build-python

# Controls when the workflow will run
on:
  # this is a called workflow
  workflow_call:
    outputs:
      build-file:
        description: "The output of this build procsss"
        value: ${{ jobs.linux-build-job.outputs.install-file }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the installer on mac
  linux-build-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Output
    outputs:
      install-file: ${{ steps.output-installer.outputs.filename }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Setup python
      - name: System Setup
        run: |
          pip3 install setuptools 

      # Build the installer
      - name: Build Python Installer
        run: |
          python setup.py sdist
          
      - uses: actions/upload-artifact@v3
        with:
          name: python-install-package
          path: dist

      - id: output-installer
        run: echo "::set-output name=filename::python-install-package"
        
        
