# This is a basic workflow to help you get started with Actions

name: build-linux

# Controls when the workflow will run
on:
  # this is a called workflow
  workflow_call:
    outputs:
      build-file:
        description: "The output of this build procsss"
        value: ${{ jobs.linux-build-job.outputs.install-file }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the installer on mac
  linux-build-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Output
    outputs:
      install-file: ${{ steps.output-installer.outputs.filename }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Setup python
      - name: System Setup
        run: |
          pip install pyinstaller pyqt5 darkdetect argparse intelhex esptool

      # Build the installer
      - name: Build Linux Installer
        run: |
          ESPTOOL_LOCATION=$(pip show esptool | grep "Location: " | cut -c 11- | tr -d '\n')
          ESPTOOL_TARGETS=$(echo "${ESPTOOL_LOCATION}/esptool/targets/stub_flasher/*:esptool/targets/stub_flasher/")
          pyinstaller --onefile --clean --name RTKUploader --noconsole --distpath=. --icon=RTK_Firmware_Uploader/resource/RTK.ico --add-data="RTK_Firmware_Uploader/resource/*:resource/" --add-data="${ESPTOOL_TARGETS}" RTK_Firmware_Upload.py
          gzip RTKUploader
          mv RTKUploader.gz RTKUploader.linux.gz
          
      - uses: actions/upload-artifact@v3
        with:
          name: RTKUploader.linux.gz
          path: RTKUploader.linux.gz

      - id: output-installer
        run: echo "filename=RTKUploader.linux.gz" >> $GITHUB_OUTPUT
